import assert from 'node:assert/strict'
import fs from 'node:fs/promises'
import path from 'node:path'
import test from 'node:test'

const UI_DIR = path.join(process.cwd(), 'packages', 'ui')

async function readUiFile(relativePath: string) {
  return fs.readFile(path.join(UI_DIR, relativePath), 'utf8')
}

test('touchable primitive drops unused legacy opacity override props', async () => {
  const source = await readUiFile(path.join('primitives', 'Touchable.tsx'))
  const primitiveIndex = await readUiFile(path.join('primitives', 'index.ts'))

  assert.doesNotMatch(source, /disabledOpacity\?: number/)
  assert.doesNotMatch(source, /pressedOpacity\?: number/)
  assert.doesNotMatch(source, /hoveredOpacity\?: number/)
  assert.match(source, /opacity\.disabled/)
  assert.match(source, /opacity\.medium/)
  assert.match(source, /opacity\.high/)
  assert.doesNotMatch(primitiveIndex, /export \* from '\.\/Touchable'/)
})

test('phase 6 cleanup removes button-like Touchable usage from core shared components', async () => {
  const navChip = await readUiFile(path.join('components', 'NavChip.tsx'))
  const promoStrip = await readUiFile(path.join('components', 'MarketplacePromoStrip.tsx'))
  const railState = await readUiFile(path.join('components', 'HorizontalRailState.tsx'))
  const sectionHeader = await readUiFile(path.join('components', 'MarketplaceSectionHeader.tsx'))
  const footerNewsletter = await readUiFile(path.join('components', 'chrome', 'FooterNewsletter.tsx'))
  const miniSearchBar = await readUiFile(path.join('components', 'chrome', 'MiniSearchBar.tsx'))
  const searchOverlay = await readUiFile(path.join('components', 'chrome', 'SearchOverlay.tsx'))
  const loyaltyCta = await readUiFile(path.join('components', 'home-v2', 'NewsletterLoyaltyCta.tsx'))
  const carouselControls = await readUiFile(path.join('components', 'HeroCarouselControls.tsx'))
  const homeBrandRail = await readUiFile(path.join('components', 'home', 'HomeBrandRail.tsx'))
  const homeCategoryStrip = await readUiFile(path.join('components', 'home', 'HomeCategoryStrip.tsx'))
  const topBrandsGrid = await readUiFile(path.join('components', 'home-v2', 'TopBrandsGrid.tsx'))
  const ugcGallery = await readUiFile(path.join('components', 'home-v2', 'UgcGallery.tsx'))
  const testimonialsBlock = await readUiFile(path.join('components', 'home-v2', 'TestimonialsBlock.tsx'))
  const productRail = await readUiFile(path.join('components', 'home-v2', 'ProductRail.tsx'))
  const offerBannersGrid = await readUiFile(path.join('components', 'home-v2', 'OfferBannersGrid.tsx'))
  const brandSpotlightPanel = await readUiFile(path.join('components', 'home-v2', 'BrandSpotlightPanel.tsx'))
  const footerAccordion = await readUiFile(path.join('components', 'chrome', 'FooterAccordion.tsx'))
  const announcementTicker = await readUiFile(path.join('components', 'home-v2', 'AnnouncementTicker.tsx'))
  const categoryRail = await readUiFile(path.join('components', 'home-v2', 'CategoryRail.tsx'))
  const editorialHotspotSection = await readUiFile(path.join('components', 'home-v2', 'EditorialHotspotSection.tsx'))
  const heroTileRail = await readUiFile(path.join('components', 'home-v2', 'HeroTileRail.tsx'))
  const campaignHeroBlock = await readUiFile(path.join('components', 'home-v2', 'CampaignHeroBlock.tsx'))
  const flashSaleBand = await readUiFile(path.join('components', 'home-v2', 'FlashSaleBand.tsx'))
  const topPromoBar = await readUiFile(path.join('components', 'chrome', 'TopPromoBar.tsx'))
  const campaignCard = await readUiFile(path.join('components', 'CampaignCard.tsx'))
  const heroSlideCard = await readUiFile(path.join('components', 'HeroSlideCard.tsx'))
  const headerMainRow = await readUiFile(path.join('components', 'chrome', 'HeaderMainRow.tsx'))
  const footerColumns = await readUiFile(path.join('components', 'chrome', 'FooterColumns.tsx'))
  const footerSocialLinks = await readUiFile(path.join('components', 'chrome', 'FooterSocialLinks.tsx'))
  const footerAccordionSource = await readUiFile(path.join('components', 'chrome', 'FooterAccordion.tsx'))
  const drawer = await readUiFile(path.join('components', 'Drawer.tsx'))
  const cartDrawer = await readUiFile(path.join('components', 'chrome', 'CartDrawer.tsx'))

  assert.doesNotMatch(navChip, /\bTouchable\b/)
  assert.match(navChip, /<Button/)
  assert.doesNotMatch(promoStrip, /\bTouchable\b/)
  assert.match(promoStrip, /<Button/)
  assert.doesNotMatch(railState, /\bTouchable\b/)
  assert.match(railState, /<Button/)
  assert.doesNotMatch(sectionHeader, /\bTouchable\b/)
  assert.match(sectionHeader, /<Button/)
  assert.doesNotMatch(footerNewsletter, /\bTouchable\b/)
  assert.match(footerNewsletter, /<ReusableButton/)
  assert.doesNotMatch(miniSearchBar, /\bTouchable\b/)
  assert.match(miniSearchBar, /<ReusableButton/)
  assert.doesNotMatch(searchOverlay, /\bTouchable\b/)
  assert.match(searchOverlay, /<ReusableButton/)
  assert.doesNotMatch(loyaltyCta, /\bTouchable\b/)
  assert.match(loyaltyCta, /<Button/)
  assert.doesNotMatch(carouselControls, /\bTouchable\b/)
  assert.match(carouselControls, /<IconButton/)
  assert.match(carouselControls, /<ReusableButton/)
  assert.doesNotMatch(headerMainRow, /\bTouchable\b/)
  assert.match(headerMainRow, /<ReusableButton/)
  assert.doesNotMatch(footerColumns, /\bTouchable\b/)
  assert.match(footerColumns, /<ReusableButton/)
  assert.doesNotMatch(footerSocialLinks, /\bTouchable\b/)
  assert.match(footerSocialLinks, /<ReusableButton/)
  assert.doesNotMatch(footerAccordionSource, /\bTouchable\b/)
  assert.match(footerAccordionSource, /<ReusableButton/)
  assert.doesNotMatch(drawer, /\bTouchable\b/)
  assert.match(drawer, /<ReusableButton/)
  assert.doesNotMatch(cartDrawer, /\bTouchable\b/)
  assert.match(cartDrawer, /<ReusableButton/)
  assert.doesNotMatch(homeBrandRail, /\bTouchable\b/)
  assert.match(homeBrandRail, /<ReusableButton/)
  assert.doesNotMatch(homeCategoryStrip, /\bTouchable\b/)
  assert.match(homeCategoryStrip, /<ReusableButton/)
  assert.doesNotMatch(topBrandsGrid, /\bTouchable\b/)
  assert.match(topBrandsGrid, /<ReusableButton/)
  assert.doesNotMatch(ugcGallery, /\bTouchable\b/)
  assert.match(ugcGallery, /<Button/)
  assert.match(ugcGallery, /<ReusableButton/)
  assert.doesNotMatch(testimonialsBlock, /\bTouchable\b/)
  assert.match(testimonialsBlock, /<ReusableButton/)
  assert.doesNotMatch(productRail, /\bTouchable\b/)
  assert.match(productRail, /<IconButton/)
  assert.match(productRail, /<Button/)
  assert.match(productRail, /<ReusableButton/)
  assert.match(offerBannersGrid, /<ReusableButton/)
  assert.match(brandSpotlightPanel, /<ReusableButton/)
  assert.match(footerAccordion, /<ReusableButton/)
  assert.doesNotMatch(announcementTicker, /\bTouchable\b/)
  assert.match(announcementTicker, /<ReusableButton/)
  assert.doesNotMatch(categoryRail, /\bTouchable\b/)
  assert.match(categoryRail, /<IconButton/)
  assert.match(categoryRail, /<ReusableButton/)
  assert.match(editorialHotspotSection, /<Button variant='primaryCommerce'/)
  assert.doesNotMatch(editorialHotspotSection, /\bTouchable\b/)
  assert.match(editorialHotspotSection, /<ReusableButton/)
  assert.match(heroTileRail, /<IconButton/)
  assert.doesNotMatch(heroTileRail, /\bTouchable\b/)
  assert.match(heroTileRail, /<ReusableButton/)
  assert.doesNotMatch(campaignHeroBlock, /\bTouchable\b/)
  assert.match(campaignHeroBlock, /<Button/)
  assert.doesNotMatch(flashSaleBand, /\bTouchable\b/)
  assert.match(flashSaleBand, /<Button/)
  assert.doesNotMatch(topPromoBar, /\bTouchable\b/)
  assert.match(topPromoBar, /<ReusableButton/)
  assert.doesNotMatch(campaignCard, /\bTouchable\b/)
  assert.match(campaignCard, /<ReusableButton/)
  assert.doesNotMatch(heroSlideCard, /\bTouchable\b/)
  assert.match(heroSlideCard, /<ReusableButton/)
  assert.doesNotMatch(offerBannersGrid, /\bTouchable\b/)
  assert.doesNotMatch(offerBannersGrid, /<Button/)
  assert.match(offerBannersGrid, /<ReusableButton/)
  assert.doesNotMatch(brandSpotlightPanel, /\bTouchable\b/)
  assert.match(brandSpotlightPanel, /<ReusableButton/)
})
