export const UGC_COPY = {
  title: 'UGC Gallery',
  subtitle: 'Manage the curated grid of customer and social photos displayed on the homepage.',
  save: 'Save',
  saving: 'Saving…',
  success: 'UGC gallery saved successfully.',
  loading: 'Loading…',
  photos: 'Photos',
  noPhotos: 'No photos yet. Add one below.',
  addPhoto: 'Add Photo',
  imageUrl: 'Image URL',
  imageUrlPlaceholder: 'https://example.com/photo.jpg',
  caption: 'Caption',
  captionPlaceholder: 'Optional caption text',
  sourceHandle: 'Source Handle',
  sourceHandlePlaceholder: '@username',
  displayOrder: 'Display Order',
  showOnHomepage: 'Show on homepage',
  photoLabel: 'Photo',
  previewAlt: 'preview',
  loadError: 'Unable to load UGC gallery.',
  saveError: 'Unable to save UGC gallery.',
} as const
