export const endpoints = {
  products: '/api/products',
  productsFiltered: (query: string) => `/api/products${query ? `?${query}` : ''}`,
  product: (id: string) => `/api/products/${id}`,
  categories: '/api/categories',
  categoryTree: '/api/categories/tree',
  category: (slug: string) => `/api/categories/${slug}`,
  brands: '/api/brands',
  brand: (slug: string) => `/api/brands/${slug}`,
  productQueries: '/api/product-queries',
  productQuery: (slug: string) => `/api/product-queries/${slug}`,
  search: (query: string) => `/api/search?q=${encodeURIComponent(query)}`,
  cart: '/api/cart',
  cartAdd: '/api/cart/add',
  cartRemove: '/api/cart/remove',
  cartSetQuantity: '/api/cart/set-quantity',
  checkoutQuote: '/api/checkout/quote',
  orders: '/api/orders',
  order: (id: string) => `/api/orders/${id}`,
  orderPlace: '/api/orders/place',
  adminOrderStatus: (id: string) => `/api/admin/orders/${id}/status`,
  adminCache: '/api/admin/cache',
  adminCacheSettings: '/api/admin/cache/settings',
  adminCmsToggles: '/api/admin/cms/toggles',
  adminCmsToggle: (id: string) => `/api/admin/cms/toggles/${id}`,
  adminCmsBrandSpotlights: '/api/admin/cms/brand-spotlights',
  adminCmsBrandSpotlight: (id: string) => `/api/admin/cms/brand-spotlights/${id}`,
  adminCmsBanners: '/api/admin/cms/banners',
  adminCmsUgc: '/api/admin/cms/ugc',
  adminCmsSiteConfig: '/api/admin/cms/site-config',
  adminCmsSiteConfigLogoUpload: '/api/admin/cms/site-config/logo-upload',
  adminCmsOfferBanners: '/api/admin/cms/offer-banners',
  adminCmsOfferBanner: (id: string) => `/api/admin/cms/offer-banners/${id}`,
  adminCmsOfferBannersUpload: '/api/admin/cms/offer-banners/upload',
  adminCmsBlocksUpload: '/api/admin/cms/blocks/upload',
  adminCmsMenus: '/api/admin/cms/menus',
  adminCmsMenu: (id: string) => `/api/admin/cms/menus/${id}`,
  adminUsers: '/api/admin/users',
  adminUser: (id: string) => `/api/admin/users/${id}`,
  adminProducts: '/api/admin/products',
  adminProductCreate: '/api/admin/products/create',
  adminProduct: (id: string) => `/api/admin/products/${id}`,
  adminProductAction: (id: string) => `/api/admin/products/${id}/actions`,
  adminProductFields: '/api/admin/product-fields',
  adminOrders: '/api/admin/orders',
  adminOrder: (id: string) => `/api/admin/orders/${id}`,
  adminOrderAction: (id: string) => `/api/admin/orders/${id}/actions`,
  adminOrderFields: '/api/admin/order-fields',
  adminInventory: '/api/admin/inventory',
  adminInventoryItem: (id: string) => `/api/admin/inventory/${id}`,
  adminInventoryAction: (id: string) => `/api/admin/inventory/${id}/actions`,
  adminInventoryFields: '/api/admin/inventory-fields',
  adminVendors: '/api/admin/vendors',
  adminVendor: (id: string) => `/api/admin/vendors/${id}`,
  adminVendorAction: (id: string) => `/api/admin/vendors/${id}/actions`,
  adminVendorFields: '/api/admin/vendor-fields',
  adminSavedViews: '/api/admin/saved-views',
  adminCapabilities: '/api/admin/capabilities',
  adminJobs: '/api/admin/jobs',
  adminJob: (id: string) => `/api/admin/jobs/${id}`,
  adminOpsAudit: '/api/admin/ops/audit',
  adminOpsAuditExport: '/api/admin/ops/audit/export',
  adminI18nStatus: '/api/admin/i18n/status',
  adminI18nPrefill: '/api/admin/i18n/prefill',
  adminReleases: '/api/admin/releases',
  adminRelease: (id: string) => `/api/admin/releases/${id}`,
  adminReleasePublish: (id: string) => `/api/admin/releases/${id}/publish`,
  adminReleaseRollback: (id: string) => `/api/admin/releases/${id}/rollback`,
  adminPreviewToken: '/api/admin/preview-token',
  adminReleaseBlocks: '/api/admin/release-blocks',
  adminReleaseBlock: (id: string) => `/api/admin/release-blocks/${id}`,
  adminProductQueries: '/api/admin/product-queries',
  adminProductQuery: (slug: string) => `/api/admin/product-queries/${slug}`,
  adminCatalogProductColumns: '/api/admin/catalog/products/columns',
  adminCategories: '/api/admin/catalog/categories',
  adminCategory: (id: string) => `/api/admin/catalog/categories/${id}`,
  adminCategoriesSync: '/api/admin/catalog/categories/sync',
  adminBrandsAdmin: '/api/admin/catalog/brands',
  adminBrandAdmin: (id: string) => `/api/admin/catalog/brands/${id}`,
  adminBrandsAdminSync: '/api/admin/catalog/brands/sync',
  adminPromotions: '/api/admin/promotions',
  adminPromotion: (id: string) => `/api/admin/promotions/${id}`,
  reviews: (productId: string) => `/api/reviews?productId=${encodeURIComponent(productId)}`,
  reviewCreate: '/api/reviews',
  cmsHome: '/api/cms/home',
  authSession: '/api/auth/session',
  authLogin: '/api/auth/login',
  authRegister: '/api/auth/register',
  authLogout: '/api/auth/logout',
  authRequestReset: '/api/auth/request-reset',
  authResetPassword: '/api/auth/reset-password',
  accountOverview: '/api/account/overview',
  accountAddresses: '/api/account/addresses',
  accountAddress: (id: string) => `/api/account/addresses/${id}`,
  accountAddressSetDefault: (id: string) => `/api/account/addresses/${id}/set-default`,
  accountLoyalty: '/api/account/loyalty',
  accountReferral: '/api/account/referral',
  accountWishlist: '/api/account/wishlist',
  accountTests: '/api/account/tests',
  accountTest: (id: string) => `/api/account/tests/${id}`,
  accountQr: '/api/account/qr',
  referralValidate: '/api/referral/validate',
  referralApply: '/api/referral/apply',
  adminReferralSettings: '/api/admin/referral/settings',
  adminReferralProfiles: '/api/admin/referral/profiles',
  adminReferralProfile: (id: string) => `/api/admin/referral/profiles/${id}`,
  adminReferralProfileRegenerate: (id: string) => `/api/admin/referral/profiles/${id}/regenerate`,
  adminReferralLedger: '/api/admin/referral/ledger',
  pharmacistCustomersSearch: (query: string) =>
    `/api/pharmacist/customers/search?q=${encodeURIComponent(query)}`,
  pharmacistCustomer: (id: string) => `/api/pharmacist/customers/${id}`,
  pharmacistProductsSearch: (query: string) =>
    `/api/pharmacist/products/search?q=${encodeURIComponent(query)}`,
  pharmacistResolveQr: '/api/pharmacist/scan/resolve',
  pharmacistConsultationDraft: '/api/pharmacist/consultations/draft',
  pharmacistConsultationSubmit: '/api/pharmacist/consultations/submit',
} as const
