export const endpoints = {
  products: '/api/products',
  productsFiltered: (query: string) => `/api/products${query ? `?${query}` : ''}`,
  product: (id: string) => `/api/products/${id}`,
  categories: '/api/categories',
  categoryTree: '/api/categories/tree',
  category: (slug: string) => `/api/categories/${slug}`,
  brands: '/api/brands',
  brand: (slug: string) => `/api/brands/${slug}`,
  productQueries: '/api/product-queries',
  productQuery: (slug: string) => `/api/product-queries/${slug}`,
  search: (query: string) => `/api/search?q=${encodeURIComponent(query)}`,
  cart: '/api/cart',
  cartAdd: '/api/cart/add',
  cartRemove: '/api/cart/remove',
  cartSetQuantity: '/api/cart/set-quantity',
  checkoutQuote: '/api/checkout/quote',
  orders: '/api/orders',
  order: (id: string) => `/api/orders/${id}`,
  orderPlace: '/api/orders/place',
  adminOrderStatus: (id: string) => `/api/admin/orders/${id}/status`,
  adminCache: '/api/admin/cache',
  adminCmsToggles: '/api/admin/cms/toggles',
  adminCmsToggle: (id: string) => `/api/admin/cms/toggles/${id}`,
  adminCmsBrandSpotlights: '/api/admin/cms/brand-spotlights',
  adminCmsBrandSpotlight: (id: string) => `/api/admin/cms/brand-spotlights/${id}`,
  adminUsers: '/api/admin/users',
  adminUser: (id: string) => `/api/admin/users/${id}`,
  adminOpsAudit: '/api/admin/ops/audit',
  adminOpsAuditExport: '/api/admin/ops/audit/export',
  adminI18nStatus: '/api/admin/i18n/status',
  adminI18nPrefill: '/api/admin/i18n/prefill',
  adminReleases: '/api/admin/releases',
  adminRelease: (id: string) => `/api/admin/releases/${id}`,
  adminReleasePublish: (id: string) => `/api/admin/releases/${id}/publish`,
  adminReleaseBlocks: '/api/admin/release-blocks',
  adminReleaseBlock: (id: string) => `/api/admin/release-blocks/${id}`,
  adminProductQueries: '/api/admin/product-queries',
  adminProductQuery: (slug: string) => `/api/admin/product-queries/${slug}`,
  adminPromotions: '/api/admin/promotions',
  adminPromotion: (id: string) => `/api/admin/promotions/${id}`,
  reviews: (productId: string) => `/api/reviews?productId=${encodeURIComponent(productId)}`,
  reviewCreate: '/api/reviews',
  cmsHome: '/api/cms/home',
  authSession: '/api/auth/session',
  authLogin: '/api/auth/login',
  authRegister: '/api/auth/register',
  authLogout: '/api/auth/logout',
  authRequestReset: '/api/auth/request-reset',
  authResetPassword: '/api/auth/reset-password',
  accountOverview: '/api/account/overview',
  accountAddresses: '/api/account/addresses',
  accountAddress: (id: string) => `/api/account/addresses/${id}`,
  accountAddressSetDefault: (id: string) => `/api/account/addresses/${id}/set-default`,
  accountLoyalty: '/api/account/loyalty',
  accountWishlist: '/api/account/wishlist',
  accountTests: '/api/account/tests',
  accountTest: (id: string) => `/api/account/tests/${id}`,
  accountQr: '/api/account/qr',
  pharmacistCustomersSearch: (query: string) =>
    `/api/pharmacist/customers/search?q=${encodeURIComponent(query)}`,
  pharmacistCustomer: (id: string) => `/api/pharmacist/customers/${id}`,
  pharmacistProductsSearch: (query: string) =>
    `/api/pharmacist/products/search?q=${encodeURIComponent(query)}`,
  pharmacistResolveQr: '/api/pharmacist/scan/resolve',
  pharmacistConsultationDraft: '/api/pharmacist/consultations/draft',
  pharmacistConsultationSubmit: '/api/pharmacist/consultations/submit',
} as const
