import { StylesProvider } from './styles-provider'
import './globals.css'
import { Cairo } from 'next/font/google'
import { resolveDirection } from '@real/app/lib/rtl-manager'
import { resolvePageLocale } from './_lib/locale'
import { initI18n } from '@real/app/lib/i18n'

const cairo = Cairo({
  subsets: ['latin', 'arabic'],
  display: 'swap',
  variable: '--font-cairo',
  weight: ['400', '500', '600', '700'],
})

export const metadata = {
  title: 'Create Solito App',
  description: 'Generated by create Solito app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const locale = await resolvePageLocale()
  const direction = resolveDirection(locale)
  await initI18n(locale)

  return (
    <html lang={locale} dir={direction} className={cairo.variable}>
      <body>
        <StylesProvider>{children}</StylesProvider>
      </body>
    </html>
  )
}
