import { colors } from './colors'
import { glass, scrim } from './opacity'
import { fontFamilies, fontWeights } from './typography'

export const buttonTokens = {
  height: {
    sm: 44,  // WCAG 2.5.5: minimum 44px touch target
    md: 44,  // WCAG 2.5.5: minimum 44px touch target
    lg: 48,
  },
  paddingX: {
    sm: 12,
    md: 14,
    lg: 16,
  },
  minWidth: {
    system: 192,
    feedback: 117,
  },
  radius: {
    default: 8,
    quiet: 0,
    pill: 9999,
  },
  icon: {
    md: 20,
    lg: 24,
  },
} as const

export const iconButtonTokens = {
  size: {
    md: 44,  // WCAG 2.5.5: minimum 44px touch target
    lg: 44,  // WCAG 2.5.5: minimum 44px touch target
  },
  icon: {
    md: 16,
    lg: 18,
  },
  radius: {
    default: 0,
    pill: 9999,
  },
} as const

export const inputTokens = {
  height: {
    sm: 34,
    md: 38,
  },
  paddingX: {
    sm: 10,
    md: 12,
  },
  radius: {
    default: 6,
    pill: 9999,
  },
} as const

export const cardTokens = {
  radius: {
    product: 4,
    promo: 4,
    brand: 4,
    feedback: 4,
  },
  width: {
    product: 334,
    category: 324,
    brand: 324,
    banner: 840,
  },
  mediaRatio: {
    product: 1,
  },
} as const

export const sectionHeadingTokens = {
  titleArcWidth: 88,
  titleArcHeight: 12,
  titleGapY: 6,
} as const

export const headerTokens = {
  fonts: {
    display: fontFamilies.logo,
    body: fontFamilies.logoSecondary,
  },
  utility: {
    dotSize: 4,
    topBarTextSize: 10,
    topBarTextLineHeight: 14,
    topBarTextTracking: 1.6,
    socialIconSize: 13,
  },
  brand: {
    wordmarkSize: 35,
    wordmarkLineHeight: 33,
    wordmarkTracking: -2.1,
    wordmarkWeight: fontWeights.medium,
    subtitleSize: 10,
    subtitleLineHeight: 12,
    subtitleTracking: 2.4,
    subtitleWeight: fontWeights.bold,
    accentArcWidth: 82,
    accentArcHeight: 8,
    accentArcOffsetY: 1,
    accentArcThickness: 2,
    taglineSize: 11,
    taglineLineHeight: 13,
    taglineTracking: 0.25,
    taglineWeight: fontWeights.medium,
    logoImageHeightSm: 28,
    logoImageHeightMd: 38,
    logoImageHeightLg: 48,
    logoImageMaxWidthSm: 96,
    logoImageMaxWidthMd: 132,
    logoImageMaxWidthLg: 168,
  },
  actions: {
    buttonSize: 40,
    iconSize: 21,
    badgeSize: 18,
  },
  search: {
    departmentsHeight: 44,
    departmentsPaddingX: 16,
    departmentsGap: 4,
    departmentsTextSize: 12,
    departmentsTextLineHeight: 16,
    searchRightHighlightWidth: 112,
    searchTopHighlightWidth: 64,
  },
  controls: {
    inlineHeight: 38,
    inlineGap: 6,
    inlinePaddingX: 14,
    inlinePaddingY: 6,
    inlineIconSize: 18,
    inlineTextSize: 11,
    inlineTextLineHeight: 16,
    inlineTextTracking: 1.54,
    inlineCaretSize: 14,
  },
  quickActions: {
    itemHeight: 36,
    itemGap: 8,
    rowPaddingY: 12,
    itemPaddingX: 10,
    textSize: 11,
    textLineHeight: 18,
    textTracking: 1.32,
    iconSize: 12,
  },
  mobile: {
    headerPaddingTop: 12,
    headerPaddingBottom: 14,
    compactPaddingTop: 10,
    compactPaddingBottom: 10,
    stackGap: 10,
    deliveryGap: 6,
    deliveryIconSize: 16,
    deliveryLabelSize: 12,
    deliveryLabelLineHeight: 16,
    deliveryValueSize: 14,
    deliveryValueLineHeight: 18,
    deliveryTracking: 0.2,
    searchHeight: 48,
    searchRadius: 999,
    searchIconSize: 18,
    searchTextSize: 16,
    searchTextLineHeight: 20,
    actionButtonSize: 48,
    actionIconSize: 22,
    actionGap: 10,
  },
} as const

export const storefrontHomeTokens = {
  contentPaddingXDesktop: 16,
  contentPaddingXMobile: 12,
  cta: {
    minHeight: 38,
    paddingX: 14,
    paddingY: 7,
    gap: 4,
    iconSize: 14,
    textSize: 11,
    textTracking: 1.2,
    primaryRadius: 8,
    secondaryRadius: 6,
    primaryBackground: colors.ctaBackground,
    primaryBackgroundHover: colors.gray50,
    primaryTextColor: colors.white,
    secondaryBackground: colors.surface,
    secondaryBackgroundHover: colors.surfaceMuted,
    secondaryTextColor: colors.textPrimary,
    secondaryBorderColor: 'transparent',
  },
  layout: {
    rootGap: 16,
    sectionGap: 12,
    categorySectionGap: 12,
    categorySectionPaddingY: 12,
    brandSpotlightGap: 12,
    brandPanelGap: 12,
    testimonialGap: 12,
    railCueMarginTop: 4,
  },
  categoryCards: {
    desktopWidth: 216,
    mobileMinWidth: 160,
    mobileMaxWidth: 196,
    railGap: 8,
    railTopPadding: 4,
    railBottomPadding: 4,
    hoverLift: 2,
    minHeight: 108,
    mediaSize: 64,
    mediaRadius: 999,
    contentPaddingX: 16,
    contentPaddingY: 16,
    titleLineHeight: 22,
    metaLineHeight: 18,
    arrowSize: 32,
    arrowIconSize: 12,
  },
  discovery: {
    sectionGap: 12,
    chipsGap: 6,
    chipMinHeight: 32,
    chipPaddingX: 12,
    chipLabelSize: 11,
    chipLabelLineHeight: 16,
    chipLabelTracking: 1.2,
    trustGridGap: 16,
    trustCardMinHeight: 84,
    trustCardPaddingX: 16,
    trustCardPaddingY: 16,
    trustTitleSize: 12,
    trustTitleLineHeight: 16,
    trustMetaSize: 10,
    trustMetaLineHeight: 14,
    trustMetaTracking: 0.8,
    railFilterGap: 6,
    railFilterMinHeight: 34,
    railFilterPaddingX: 12,
    railFilterLabelTracking: 1.1,
  },
  hero: {
    railGap: 10,
    desktopContainerPaddingX: 16,
    mobileContainerPaddingX: 12,
    desktopVisibleCards: 4,
    desktopCardHeight: 468,
    tabletCardHeight: 404,
    mobileCardHeight: 312,
    autoScrollIntervalMs: 4200,
    imageAreaRatio: 0.8,
    panelPadding: 32,
    panelGap: 24,
    compactTriggerHeight: 180,
    compactPanelPadding: 16,
    compactPanelGap: 8,
    compactEyebrowTracking: 1.2,
    eyebrowTracking: 1.4,
    badgeTracking: 1.05,
    compactTitleSize: 18,
    compactTitleLineHeight: 21,
    compactTitleMinHeight: 24,
    compactSubtitleSize: 12,
    compactSubtitleMinHeight: 16,
    compactSubtitleLineHeight: 17,
    topRowGap: 12,
    badgeMinHeight: 24,
    badgeGap: 4,
    badgePaddingX: 12,
    badgePaddingY: 4,
    badgeIconWrapSize: 16,
    badgeIconSize: 14,
    titleSize: 24,
    titleLineHeight: 28,
    titleMinHeight: 56,
    titleTracking: -0.6,
    subtitleSize: 13,
    subtitleMinHeight: 56,
    subtitleLineHeight: 19,
    subtitleOpacity: 0.84,
    taglineMarginTop: 10,
    taglineTracking: 1.6,
  },
  editorialHotspot: {
    desktopImageSize: 500,
    tabletImageSize: 360,
  },
  topBrands: {
    sectionGap: 16,
    desktopColumns: 6,
    desktopGap: 12,
    mobileGap: 12,
    tileSizeDesktop: 112,
    tileSizeMobile: 96,
    tilePaddingXDesktop: 12,
    tilePaddingXMobile: 10,
    tileTextSizeDesktop: 16,
    tileTextSizeMobile: 12,
    tileTextLineHeightDesktop: 20,
    tileTextLineHeightMobile: 16,
    tileTextTracking: 0.4,
    tileTextMaxWidthRatio: 0.78,
    hoverLift: 2,
  },
  offers: {
    sectionGap: 12,
    rowGap: 10,
    cardMinHeightDesktop: 250,
    cardMinHeightMobile: 250,
    cardPaddingDesktop: 16,
    cardPaddingMobile: 14,
    cardPaddingBottomDesktop: 18,
    cardPaddingBottomMobile: 14,
    copyMaxWidth: 320,
    contentGap: 6,
    eyebrowOpacity: 0.7,
    eyebrowTracking: 1.98,
    titleFontSizeDesktop: 24,
    titleFontSizeMobile: 19,
    titleLineHeightDesktop: 27,
    titleLineHeightMobile: 22,
    titleTracking: -0.7,
    saleFontSizeDesktop: 46,
    saleFontSizeMobile: 34,
    saleLineHeightDesktop: 44,
    saleLineHeightMobile: 34,
    saleTracking: -2.2,
    subtitleFontSize: 13,
    subtitleOpacity: 0.88,
    subtitleLineHeight: 19,
    ctaBorderColor: glass.offerBannerCtaBorder,
    ctaBackgroundColor: glass.offerBannerCta,
    ctaHoverBackgroundColor: glass.offerBannerCtaHover,
    ctaHoverTextColor: colors.inkBlack,
    imageOverlayFallback: scrim.offerBannerMediaNative,
    imageOverlayGradient: scrim.offerBannerMedia,
    radialOverlayTopOffer: 'none',
    radialOverlayBundleEdit: 'none',
    glossOverlay: glass.offerBannerGloss,
  },
  product: {
    railGap: 8,
    columns: {
      desktop: 5,
      tablet: 4,
      mobile: 2,
    },
    desktopMinWidth: 132,
    navButtonSize: 32,
    navIconSize: 14,
    navEdgeOffset: 8,
    navTopFactor: 0.5,
  },
  productCard: {
    defaultWidth: 200,
    cardGap: 4,
    contentGap: 4,
    contentPaddingX: 8,
    contentPaddingY: 6,
    cardHoverLift: 0,
    shellBorderColor: 'transparent',
    shellBorderWidth: 0,
    shellShadowRest: '0 4px 14px rgba(20,18,15,0.05)',
    shellShadowHover: '0 8px 24px rgba(20,18,15,0.08)',
    mediaHoverScale: 1,
    mediaOverlayOpacity: 0,
    quickActionsInset: 4,
    quickActionsGap: 4,
    quickActionsWrapPaddingX: 6,
    quickActionsWrapPaddingY: 6,
    quickActionsRevealOffsetX: 8,
    quickActionSize: 32,
    quickActionIconSize: 14,
    quickActionShadowRest: '0 4px 12px rgba(20,18,15,0.05)',
    quickActionShadowHover: '0 8px 20px rgba(20,18,15,0.08)',
    quickActionLabelGap: 6,
    quickActionLabelMinHeight: 24,
    quickActionLabelPaddingX: 10,
    quickActionLabelFontSize: 10,
    quickActionLabelLineHeight: 13,
    quickActionLabelTracking: 0.4,
    badgeTopInset: 4,
    badgeSideInset: 4,
    badgeGap: 4,
    badgeScale: 0.92,
    brandFontSize: 10,
    brandLineHeight: 12,
    brandTracking: 1.4,
    nameFontSize: 12,
    nameLineHeight: 15,
    nameMinHeight: 30,
    subtitleFontSize: 11,
    subtitleLineHeight: 13,
    subtitleMinHeight: 14,
    attributesFontSize: 10,
    attributesLineHeight: 12,
    attributesMinHeight: 12,
    ratingMinHeight: 16,
    ratingSize: 10,
    priceRowMinHeight: 24,
    priceGap: 4,
    priceFontSize: 15,
    priceLineHeight: 17,
    compareFontSize: 11,
    compareLineHeight: 13,
    unitPriceFontSize: 10,
    unitPriceLineHeight: 14,
    urgencyMinHeight: 14,
    urgencyFontSize: 9,
    urgencyLineHeight: 12,
    urgencyTracking: 0.8,
    buyActionMinWidth: 96,
    buyActionHeight: 32,
    quantityChipMinWidth: 28,
    quantityStepperMinWidth: 82,
    quantityStepperInset: 4,
    quantityStepperActionWidth: 24,
    buyActionGap: 4,
    buyActionIconSize: 12,
    buyActionTextSize: 11,
    buyActionTextTracking: 0.1,
    buyActionShadowRest: '0 0 0 1px rgba(183,24,44,0.12), 0 6px 14px rgba(183,24,44,0.14)',
    buyActionShadowHover: '0 0 0 1px rgba(183,24,44,0.18), 0 10px 22px rgba(183,24,44,0.24)',
  },
  productCardDensity: {
    comfortable: {
      cardGap: 6,
      contentGap: 4,
      contentPaddingX: 12,
      contentPaddingY: 6,
      quickActionSize: 32,
      quickActionIconSize: 14,
      quickActionLabelFontSize: 10,
      quickActionLabelLineHeight: 13,
      badgeScale: 0.88,
      brandFontSize: 10,
      brandLineHeight: 13,
      nameFontSize: 13,
      nameLineHeight: 16,
      nameMinHeight: 32,
      ratingSize: 9,
      priceFontSize: 15,
      priceLineHeight: 18,
      compareFontSize: 11,
      compareLineHeight: 14,
      urgencyFontSize: 9,
      urgencyLineHeight: 13,
      buyActionHeight: 40,
      buyActionIconSize: 14,
      buyActionTextSize: 13,
      quantityChipMinWidth: 36,
      quantityStepperMinWidth: 108,
      quantityStepperActionWidth: 34,
      mediaAspectRatio: 1,
    },
    compact: {
      cardGap: 6,
      contentGap: 4,
      contentPaddingX: 12,
      contentPaddingY: 6,
      quickActionSize: 32,
      quickActionIconSize: 14,
      quickActionLabelFontSize: 10,
      quickActionLabelLineHeight: 13,
      badgeScale: 0.82,
      brandFontSize: 10,
      brandLineHeight: 13,
      nameFontSize: 13,
      nameLineHeight: 16,
      nameMinHeight: 32,
      ratingSize: 9,
      priceFontSize: 15,
      priceLineHeight: 18,
      compareFontSize: 11,
      compareLineHeight: 14,
      urgencyFontSize: 9,
      urgencyLineHeight: 13,
      buyActionHeight: 38,
      buyActionIconSize: 14,
      buyActionTextSize: 13,
      quantityChipMinWidth: 32,
      quantityStepperMinWidth: 96,
      quantityStepperActionWidth: 30,
      mediaAspectRatio: 1,
    },
    minimal: {
      cardGap: 3,
      contentGap: 2,
      contentPaddingX: 8,
      contentPaddingY: 4,
      quickActionSize: 24,
      quickActionIconSize: 12,
      quickActionLabelFontSize: 9,
      quickActionLabelLineHeight: 12,
      badgeScale: 0.9,
      brandFontSize: 10,
      brandLineHeight: 13,
      nameFontSize: 11,
      nameLineHeight: 13,
      nameMinHeight: 24,
      ratingSize: 8,
      priceFontSize: 13,
      priceLineHeight: 15,
      compareFontSize: 9,
      compareLineHeight: 11,
      urgencyFontSize: 8,
      urgencyLineHeight: 10,
      buyActionHeight: 30,
      buyActionIconSize: 12,
      buyActionTextSize: 11,
      quantityChipMinWidth: 24,
      quantityStepperMinWidth: 74,
      quantityStepperActionWidth: 22,
      mediaAspectRatio: 0.84,
    },
  },
  brandSpotlightRail: {
    sectionGap: 24,
    bannerMinHeightDesktop: 188,
    bannerMinHeightMobile: 156,
    bannerPaddingDesktop: 32,
    bannerPaddingMobile: 24,
    bannerCopyMaxWidth: 420,
    bannerEyebrowTracking: 1.8,
    bannerEyebrowOpacity: 0.8,
    bannerTitleFontSizeDesktop: 46,
    bannerTitleFontSizeMobile: 34,
    bannerTitleLineHeightDesktop: 44,
    bannerTitleLineHeightMobile: 36,
    bannerTitleTracking: -1.8,
    bannerSubtitleLineHeight: 24,
    bannerOverlayFallback: scrim.brandSpotlightBannerNative,
    bannerOverlayGradient: scrim.brandSpotlightBanner,
    bannerRadialGradient: scrim.brandSpotlightHighlight,
    railGap: 16,
  },
  footer: {
    topArcWidth: 1200,
    topArcHeight: 22,
    topArcOpacity: 0.72,
    topArcOffsetY: 24,
    instagramTileHeightDesktop: 112,
    instagramTileHeightMobile: 80,
    instagramColumnsDesktop: 8,
    instagramColumnsMobile: 4,
    instagramButtonHeight: 36,
    instagramButtonPaddingX: 20,
    instagramButtonTextSize: 14,
    instagramButtonTextLineHeight: 20,
    brandBlockPaddingTop: 40,
    brandBlockPaddingBottom: 24,
    wordmarkSize: 34,
    wordmarkLineHeight: 34,
    wordmarkTracking: 0.4,
    cosmeticsSize: 10,
    cosmeticsLineHeight: 14,
    cosmeticsTracking: 3.5,
    taglineSize: 12,
    taglineLineHeight: 16,
    taglineTracking: 2.0,
    mainGridGap: 32,
    sectionTitleTracking: 1.4,
    linkLineHeight: 20,
    linkOpacity: 0.75,
    newsletterMaxWidth: 332,
    legalPaddingY: 16,
    legalOpacity: 0.8,
  },
} as const

export const storefrontCommerceTokens = {
  pdp: {
    contentGap: 16,
    detailsGap: 12,
    mediaGap: 8,
    mediaThumbSize: 56,
    purchasePanelMaxWidth: 384,
    purchasePanelGap: 8,
    trustCardGap: 6,
    trustCardPadding: 10,
    stickyMobileBarPadding: 8,
    tabGap: 8,
    tabPaddingBottom: 8,
    setRowPaddingY: 8,
    relatedCardWidthDesktop: 192,
    relatedCardWidthMobile: 168,
  },
  cart: {
    listGap: 8,
    itemGap: 6,
    itemPadding: 12,
    summaryGap: 8,
    summaryPanelPadding: 12,
    stickyPanelTop: 108,
    actionButtonMinWidth: 160,
  },
  checkout: {
    contentGap: 16,
    blockGap: 12,
    summaryGap: 8,
    summaryPanelPadding: 16,
    stickyPanelTop: 108,
    stepChipMinHeight: 28,
    stepChipPaddingX: 12,
    paymentBadgeGap: 8,
    mobileActionPaddingY: 12,
  },
} as const

export const componentTokens = {
  button: buttonTokens,
  iconButton: iconButtonTokens,
  input: inputTokens,
  card: cardTokens,
  sectionHeading: sectionHeadingTokens,
  header: headerTokens,
  storefrontHome: storefrontHomeTokens,
  storefrontCommerce: storefrontCommerceTokens,
} as const
