const semanticTypeScale = {
  display2xl: 48,
  displayXl: 36,
  displayLg: 28,
  headingXl: 28,
  headingLg: 22,
  headingMd: 18,
  headingSm: 16,
  bodyLg: 16,
  bodyMd: 14,
  bodySm: 12,
  label: 12,
  caption: 11,
  small: 11,
  overline: 10,
} as const

export const typography = {
  ...semanticTypeScale,

  // Canonical semantic aliases
  display: semanticTypeScale.display2xl,
  heading: semanticTypeScale.headingLg,
  body: semanticTypeScale.bodyMd,

  // Existing product aliases kept for compatibility
  hero: semanticTypeScale.displayXl,
  campaign: semanticTypeScale.displayLg,
  h1: 20,
  h2: 18,
  h3: 16,
  h4: 14,
  h5: 13,
  h6: 12,
  headline: semanticTypeScale.headingLg,
  subheadline: semanticTypeScale.bodyMd,
  subtitle1: semanticTypeScale.bodyMd,
  subtitle2: semanticTypeScale.bodySm,
  body1: semanticTypeScale.bodyMd,
  body2: semanticTypeScale.bodySm,
  button: semanticTypeScale.label,
  meta: semanticTypeScale.small,
  nav: semanticTypeScale.label,
  price: semanticTypeScale.bodyLg,
  footer: semanticTypeScale.bodySm,

  // Legacy aliases
  xs: semanticTypeScale.small,
  sm: semanticTypeScale.bodySm,
  md: semanticTypeScale.bodyMd,
  lg: semanticTypeScale.bodyLg,
  xl: semanticTypeScale.headingLg,
  xxl: semanticTypeScale.displayLg,
  base: semanticTypeScale.bodyMd,
  '2xl': semanticTypeScale.displayLg,
  '3xl': semanticTypeScale.displayXl,
  '4xl': semanticTypeScale.display2xl,

  // Tier aliases used by existing components
  displayTier: semanticTypeScale.displayLg,
  headlineTier: semanticTypeScale.headingLg,
  subHeadlineTier: semanticTypeScale.bodyMd,
  bodyTier: semanticTypeScale.bodyMd,
  captionTier: semanticTypeScale.small,

  // Numbered heading aliases used by Text primitives
  heading6: 12,
  heading7: 14,
  heading8: 16,
  heading9: 18,
  heading10: 20,
} as const

export const fontFamilies = {
  sans: 'var(--font-manrope, "Manrope"), -apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", sans-serif',
  heading: 'var(--font-manrope, "Manrope"), -apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", sans-serif',
  display: 'var(--font-manrope, "Manrope"), -apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", sans-serif',
  secondary: 'var(--font-manrope, "Manrope"), -apple-system, system-ui, sans-serif',
  logo: 'var(--font-manrope, "Manrope"), -apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", sans-serif',
  logoSecondary: 'var(--font-manrope, "Manrope"), sans-serif',
  serif: 'var(--font-playfair, "Playfair Display"), Georgia, "Times New Roman", serif',
  arabic: 'var(--font-tajawal, "Tajawal"), -apple-system, system-ui, sans-serif',
  mono: 'Menlo, monospace',
} as const

export const fontWeights = {
  ultra: '100',
  light: '300',
  regular: '400',
  medium: '500',
  semibold: '600',
  bold: '700',
  extrabold: '800',
  black: '900',
} as const

export const lineHeights = {
  display2xl: 56,
  displayXl: 44,
  displayLg: 36,
  headingXl: 36,
  headingLg: 30,
  headingMd: 26,
  headingSm: 24,
  bodyLg: 24,
  bodyMd: 22,
  bodySm: 18,
  label: 16,
  caption: 16,
  small: 16,
  overline: 16,

  // Existing compatibility aliases
  h1: 28,
  h2: 26,
  h3: 24,
  h4: 20,
  h5: 18,
  h6: 18,
  subtitle1: 20,
  subtitle2: 18,
  body1: 22,
  body2: 18,
  button: 16,
  body: 22,
  heading: 30,
  hero: 44,
  tight: 1.15,
  normal: 1.35,
  relaxed: 1.55,
} as const

export const letterSpacing = {
  display2xl: -1.92,
  displayXl: -1.2,
  displayLg: -0.8,
  headingXl: -0.8,
  headingLg: -0.4,
  headingMd: -0.2,
  headingSm: -0.1,
  bodyLg: 0,
  bodyMd: 0,
  bodySm: 0,
  label: 0.08,
  caption: 0.06,
  small: 0.06,
  overline: 1.6,

  // Existing compatibility aliases
  h1: -1.92,
  h2: -1.2,
  h3: 0,
  h4: 0.085,
  h5: 0,
  h6: 0.03,
  subtitle1: 0.2,
  subtitle2: 0.14,
  body1: 0.08,
  body2: 0.035,
  button: 0,
  displayWide: 2.8,
  labelSmallCaps: 1.6,
  tight: -0.6,
  normal: 0,
  wide: 0.3,
  caps: 1,
  capsWide: 2,
  headlineTier: -0.8,
  subHeaderCaps: 1.2,
  campaignHeading: -1.6,
  labelPill: 1.92,
} as const
